name = "aura-artifacts-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "aura-testnet-artifacts"

[[routes]]
pattern = "artifacts.aurablockchain.org/*"
zone_name = "aurablockchain.org"
